RUC-MSc-CS-CIT-2024/portfolio_subproject_3

src/frontend/.gitignore
src/frontend/.prettierignore
src/frontend/.prettierrc
src/frontend/README.md
src/frontend/eslint.config.js
src/frontend/index.html
src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/ contexts/QueryContext.jsx
src/frontend/src/App.jsx
src/frontend/src/hooks/useFetchPersons.js
src/frontend/src/main.jsx
src/frontend/src/pages/HomePage.jsx
src/frontend/src/pages/NotFoundPage.jsx
src/frontend/src/services/baseDataService.js
src/frontend/src/services/mediaService.js
src/frontend/src/services/personService.js
src/frontend/src/services/userService.js
src/frontend/src/utils/constants.js
src/frontend/src/utils/validation.js
src/frontend/vite.config.js

This pull request includes several changes to set up the frontend project with React and Vite, configure ESLint and Prettier, and provide initial project structure and dependencies. The most important changes include setting up ESLint and Prettier configurations, creating the initial project structure, and adding essential dependencies.
* [`src/frontend/.prettierrc`](diffhunk://#diff-300d7c325f2c4ba728d352d939e30dfd8a7d14f35fb057cf776c55f0734330f5R1-R8): Added Prettier configuration file to enforce code formatting rules.
* [`src/frontend/.prettierignore`](diffhunk://#diff-9e19d6a7d25c3016990c333ee19f3f8e63331d32f0420e0b463ce9b4d155b047R1-R3): Added Prettier ignore file to exclude certain files and directories from formatting.
* [`src/frontend/eslint.config.js`](diffhunk://#diff-42362a7c58c …

feat: setting up react project

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/Layout.jsx
src/frontend/src/components/LoginForm/LoginForm.css
src/frontend/src/components/LoginForm/LoginForm.jsx
src/frontend/src/components/NavBar/NavBar.css
src/frontend/src/components/NavBar/Navbar.jsx
src/frontend/src/components/Navbar.jsx
src/frontend/src/components/SearchForm/SearchForm.jsx
src/frontend/src/contexts/AuthContext.jsx
src/frontend/src/pages/NotFoundPage.jsx
src/frontend/src/pages/PagesData.jsx
src/frontend/src/pages/ProfilePage.jsx
src/frontend/src/pages/ProfileSettingsPage.jsx
src/frontend/src/pages/Router.jsx
src/frontend/src/pages/SignInPage.jsx
src/frontend/src/pages/SignUpPage.jsx

Set up navigation for the website
* Added `NavBar` component to provide navigation functionality, including a dropdown for login and links to profile and bookmarks. (`src/frontend/src/components/NavBar/NavBar.jsx`)
* Added `LoginForm` component to handle user login with username and password fields. (`src/frontend/src/components/LoginForm/LoginForm.jsx`)
* Added `SearchForm` component to provide a search bar in the navigation. (`src/frontend/src/components/SearchForm/SearchForm.jsx`)
* Added `ProfileSettingsPage` and `SignInPage` to the routing and pages data. (`src/frontend/src/pages/PagesData.jsx`) [[1]](diffhunk://#diff-2a8bab970cc04ddbae493fea4909446ac2e4dc15ee5ab7d1e3d2f56bc4bf9675R4-R18) [[2]](diffhunk://#diff-2a8bab970cc04ddbae493fea4909446ac2e4dc15ee5ab7d1e3d2f56bc4bf9675R28-R36) …

feat: navbar component

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/DynamicBreadcrumb/DynamicBreadcrumb.jsx
src/frontend/src/components/UpdateProfileForm/UpdateProfileForm.jsx
src/frontend/src/contexts/AuthContext.jsx
src/frontend/src/pages/HomePage.jsx
src/frontend/src/pages/ProfilePage.jsx
src/frontend/src/services/authService.js
src/frontend/src/services/userService.js
src/frontend/src/utils/getUserFromSession.js

This PR includes new user profile page with components to update the profile and breadcrumb,
It also enhances user profile management and improves user authentication.
* Added `jwt-decode` version `4.0.0` to `package.json` and `package-lock.json`. [[1]](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3R15) [[2]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR12) [[3]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR3162-R3169)
* Updated `electron-to-chromium` to version `1.5.66` in `package-lock.json`.
* Updated `which-typed-array` to version `1.1.16` in `package-lock.json`.
* Created `DynamicBreadcrumb` component to render breadcrumbs dynamically.
* Created `UpdateProfileForm` component …

feat: profile settings page

---

src/frontend/src/components/MovieCard/MovieCard.css
src/frontend/src/components/MovieCard/MovieCard.jsx
src/frontend/src/components/index.js

This pull request introduces a new `MovieCard` component to the frontend, which includes both the JSX and CSS implementations. The component is designed to display movie information and handle loading states. Additionally, it has been added to the component exports.
* [`src/frontend/src/components/MovieCard/MovieCard.jsx`](diffhunk://#diff-50ce450e5571415e88f18878d3737af20569a4ddc609bac97f412ddde89b5f7cR1-R77): Implemented the `MovieCard` component, which includes handling for image loading states, default values for missing data, and navigation to a movie detail page on click.
* [`src/frontend/src/components/MovieCard/MovieCard.css`](diffhunk://#diff-a1e3e06d651526501d917dacc543d4b758cf7d4749676ae0ca657b90cf7b15eeR1-R25): Added styles for the `MovieCard` component, including styles for …

feat: set up movie card component

---

src/frontend/src/components/DefaultImage/DefaultImage.css
src/frontend/src/components/DefaultImage/DefaultImage.jsx
src/frontend/src/components/InfoRow/InfoRow.jsx
src/frontend/src/components/MediaCard/MediaCard.css
src/frontend/src/components/MediaCard/MediaCard.jsx
src/frontend/src/components/MediaInformation/MediaInformation.css
src/frontend/src/components/MediaInformation/MediaInformation.jsx
src/frontend/src/components/PlaceholderText/PlaceholderText.jsx
src/frontend/src/components/index.js
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/pages/MediaOverviewPage.jsx

This pull request introduces several new components and refactors existing ones to improve the frontend's structure and maintainability. The most important changes include the creation of `DefaultImage`, `InfoRow`, `PlaceholderText`, and `MediaInformation` components, as well as refactoring the `MediaCard` component to utilize these new components.
* [`src/frontend/src/components/DefaultImage/DefaultImage.jsx`](diffhunk://#diff-cb9bcbb8064be8e63a96eaa0562653719e219fed45b15b89f405c926b0f53e4cR1-R21): Added a new `DefaultImage` component to display a default SVG image when no image is available.
* [`src/frontend/src/components/InfoRow/InfoRow.jsx`](diffhunk://#diff-5c609caa42c1f864adc7902727253fa3b5ab077c637d73488bcd813ffed7c0d2R1-R7): Added a new `InfoRow` component to display labeled …

feat: set up media information

---

src/frontend/src/components/ActionDropdown/ActionDropdown.jsx
src/frontend/src/components/MediaActions/MediaActions.jsx
src/frontend/src/components/index.js
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/services/userService.js

This pull request introduces several new features and enhancements to the media management functionality. The most important changes include the addition of new components for user interactions, updates to the media detail page, and new service functions for handling user actions.
* [`src/frontend/src/components/ActionDropdown/ActionDropdown.jsx`](diffhunk://#diff-393ff9532e25169b4d5603c3990d9636a13b0b007bbdb525f2f713ac96e9185aR1-R60): Added a new `ActionDropdown` component that provides a form within a dropdown menu for user actions.
* [`src/frontend/src/components/MediaActions/MediaActions.jsx`](diffhunk://#diff-4378d02c209913b5c7a85ec0882bd5a5d23802bea444e4e22f0ee9928c3bcd33R1-R88): Added a new `MediaActions` component that uses `ActionDropdown` to allow users to rate media, add to …

feat: set up actions for completing, bookmarking and rating media

---

src/frontend/src/components/MediaInformation/MediaInformation.css
src/frontend/src/components/MediaInformation/MediaInformation.jsx
src/frontend/src/components/Rating/Rating.css
src/frontend/src/components/Rating/Rating.jsx
src/frontend/src/components/index.js
src/frontend/src/pages/MediaDetailPage.jsx

This pull request introduces a new `Rating` component to the `MediaInformation` section and includes some responsive design adjustments. Here are the most important changes:
* [`src/frontend/src/components/Rating/Rating.jsx`](diffhunk://#diff-952c6b33e1548b29ee68b2999a7039d6c02e057835bf1fdf45df32d408a43e9aR1-R19): Added a new `Rating` component that displays a list of ratings with their respective names and scores.
* [`src/frontend/src/components/Rating/Rating.css`](diffhunk://#diff-97feee953ee38e3bc246dca8608edce6ed20cd95a4f880190ce933b86a5cc8e4R1-R22): Created a new CSS file for the `Rating` component to style the ratings and ensure responsiveness.
* [`src/frontend/src/components/index.js`](diffhunk://#diff-812f2eaaa6f2e0da446fafe1709eb999dcbaf4fd5bb150c7f14933f2822a8a56R20): Exported …

feat: set up rating component

---

src/frontend/.env.development
src/frontend/src/services/authService.js
src/frontend/src/services/mediaService.js
src/frontend/src/services/signUpService.js
src/frontend/src/services/tmdbService.js
src/frontend/src/services/userService.js
src/frontend/src/utils/apiClient.js

This pull request focuses on refactoring the frontend services to use a new `ApiClient` class for API requests, improving code maintainability and consistency. The most important changes include replacing direct `fetch` calls with `ApiClient` methods and handling errors more consistently.
Refactoring to use `ApiClient`:
* [`src/frontend/src/services/authService.js`](diffhunk://#diff-3021e4ebef37f89dafe91e1702b77d385fbdc37cda64dd71cf62e14b8128c636L1-R22): Replaced direct `fetch` calls with `ApiClient` methods for the login functionality.
* [`src/frontend/src/services/mediaService.js`](diffhunk://#diff-337b1594ea5513a006c2589f5ce02e2b7ba67fdb8be37b75ced9be883c1b4dcfL1-R30): Replaced direct `fetch` calls with `ApiClient` methods for fetching media data.
* …

feat: update all services to use the new api client

---

src/frontend/jsconfig.json
src/frontend/src/contexts/AuthContext.jsx

This pull request includes several changes to improve the handling of user authentication and simplify path references in the frontend project. The most important changes include updating the `AuthProvider` component to handle session storage changes and adding path aliases in the `jsconfig.json` file.
Improvements to user authentication:
* [`src/frontend/src/contexts/AuthContext.jsx`](diffhunk://#diff-e293315d942711a42e6d81dc270374876410251fb776ea749df677e3de314d7eL26-R48): Updated the `useEffect` hook to check for both token and stored user, set `isAuthenticated` to false if either is missing, and added an event listener to handle session storage changes.
* [`src/frontend/src/contexts/AuthContext.jsx`](diffhunk://#diff-e293315d942711a42e6d81dc270374876410251fb776ea749df677e3de314d7eR69): …

feat: auth session validation

---

src/frontend/src/services/mediaService.js

This pull request includes significant changes to the `src/frontend/src/services/mediaService.js` file to improve the media fetching functions by using the `ApiClient` utility and enhancing error messages.
Improvements to media fetching functions:
* Replaced direct `fetch` calls with `api.Get` method from `ApiClient` for consistency and code reuse.
* Enhanced error messages to include specific media IDs and status codes for better debugging. [[1]](diffhunk://#diff-337b1594ea5513a006c2589f5ce02e2b7ba67fdb8be37b75ced9be883c1b4dcfR6-R82) [[2]](diffhunk://#diff-337b1594ea5513a006c2589f5ce02e2b7ba67fdb8be37b75ced9be883c1b4dcfL109-R107)

feat: fix import to use api client

---

src/frontend/src/pages/PersonDetailPage.jsx
src/frontend/src/services/userService.js

This pull request introduces the functionality to follow a person on the `PersonDetailPage` in the frontend. The most important changes include adding a follow button, implementing the follow action, and handling the follow request in the service layer.
* Added `Button` import from `react-bootstrap` and `createFollow` import from `userService` to `PersonDetailPage.jsx`.
* Implemented `handleFollow` function to handle the follow action, including error handling and toast messages.
* Added a follow button to the `PersonDetailPage` UI, which triggers the `handleFollow` function.
* Added `createFollow` function to `userService.js` to handle the follow request to the backend.

feat: set up logic for following a person

---

src/frontend/src/components/BookmarkList/BookmarkList.jsx
src/frontend/src/components/CompletedList/CompletedList.jsx
src/frontend/src/contexts/AuthContext.jsx
src/frontend/src/pages/ProfilePage.jsx
src/frontend/src/pages/SignUpPage.jsx
src/frontend/src/services/authService.js
src/frontend/src/services/mediaService.js
src/frontend/src/services/personService.js
src/frontend/src/services/signUpService.js
src/frontend/src/services/tmdbService.js
src/frontend/src/services/userService.js
src/frontend/src/utils/apiClient.js
src/frontend/src/utils/constants.js
src/frontend/src/utils/cookie.js

Implement support for changes to auth endpoints and user registration. Merge together with this https://github.com/RUC-MSc-CS-CIT-2024/portfolio_subproject_2/pull/94

feat: refresh token auth

---

src/frontend/src/components/UpdateProfileForm/UpdateProfileForm.jsx
src/frontend/src/pages/SignUpPage.jsx
src/frontend/src/services/signUpService.js
src/frontend/src/services/tmdbService.js

This pull request includes several changes to improve form validation, user experience, and code cleanup across multiple files in the frontend application. The most important changes include adding password length validation, modifying toast message handling, and cleaning up outdated comments and code.
Form validation improvements:
* [`src/frontend/src/components/UpdateProfileForm/UpdateProfileForm.jsx`](diffhunk://#diff-7e5330e07ba26de0f91472dfef27f201a9889399022cb908f60da59db9572f47R25-R28): Added a check to ensure the password is at least 15 characters long and displays a toast message if the condition is not met.
* [`src/frontend/src/pages/SignUpPage.jsx`](diffhunk://#diff-631d105fa93aaf3661de99a39161b19f9c365ea5d542e4f246a89a236c0f64d5R25-R30): Added a check to ensure the password is …

feat: min val password fields

---

src/frontend/src/components/CreditsList/CreditsList.jsx
src/frontend/src/components/PersonInformation/PersonInformation.jsx
src/frontend/src/components/Rating/Rating.css
src/frontend/src/components/Rating/Rating.jsx
src/frontend/src/components/index.js
src/frontend/src/global.css
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/pages/PersonDetailPage.jsx
src/frontend/src/services/personService.js
src/frontend/src/services/tmdbService.js
src/frontend/src/services/userService.js
src/frontend/src/utils/crew.js
src/frontend/src/utils/index.js

This pull request includes several changes to the frontend components and services to enhance the functionality and user experience of the application. The most important changes include the addition of a new `CreditsList` component, updates to the `PersonDetailPage` to include credits and ratings, and improvements to data fetching and handling in the services.
* [`src/frontend/src/pages/PersonDetailPage.jsx`](diffhunk://#diff-410656ca5388cae2df048377b54b05faa0a9fe86341734904e2831769706285cL3-R29): Added the `CreditsList` and `Rating` components to display a person's credits and ratings. Implemented pagination for loading more credits and updated the layout to include known media and ratings. [[1]](diffhunk://#diff-410656ca5388cae2df048377b54b05faa0a9fe86341734904e2831769706285cL3-R29) …

feat: set up credits list and know for media

---

src/frontend/src/pages/SearchPage.jsx

This pull request includes several important changes to the `SearchPage` component in `src/frontend/src/pages/SearchPage.jsx`. The changes focus on improving how media data is fetched, transformed, and displayed.
Improvements to data fetching and transformation:
* Changed the variable name from `resultList` to `response` and extracted `items` from the response in the `fetchData` function.
* Added a `transformedResults` constant to map and transform the fetched media data, adding `imageUri` and `releaseYear` properties.
Updates to data display:
* Updated the `MediaGrid` component to use `transformedResults` instead of `filteredResults`.

fix: result form search is now show

---

src/frontend/src/components/SearchForm/SearchForm.jsx

This pull request includes updates to the `SearchForm` component to improve its functionality and ensure proper handling of user authentication. The most important changes include adding a new hook, modifying the search history fetching logic, and updating the error message for better clarity.
Improvements to `SearchForm` component:
* [`src/frontend/src/components/SearchForm/SearchForm.jsx`](diffhunk://#diff-d63c9b4d81c977c527ab14269171efd40dff36598801da6596c94eb85680aa76L2-R12): Added the `useCallback` hook to optimize the `fetchSearchHistory` function and prevent unnecessary re-renders. [[1]](diffhunk://#diff-d63c9b4d81c977c527ab14269171efd40dff36598801da6596c94eb85680aa76L2-R12) [[2]](diffhunk://#diff-d63c9b4d81c977c527ab14269171efd40dff36598801da6596c94eb85680aa76L28-R35) …

fix: fix console errors and depend on the is authenticated to fetch data

---

src/frontend/src/components/GeneralCarousel/GeneralCarousel.jsx
src/frontend/src/components/PersonCard/PersonCard.css
src/frontend/src/hooks/index.js
src/frontend/src/hooks/usePaginatedData.js
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/services/mediaService.js

This pull request includes significant updates to the `MediaDetailPage` component, the addition of a new hook for paginated data, and improvements to the `GeneralCarousel` component. These changes enhance the functionality and user experience of the media detail page by implementing paginated data fetching and improving component structures.
* [`src/frontend/src/pages/MediaDetailPage.jsx`](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecR42-R67): Refactored to use the new `usePaginatedData` hook for fetching crew, cast, and similar media data, replacing previous state management and data fetching logic. This includes adding tabs for crew and cast with corresponding carousels and handling paginated data loading. …

feat: set up cast and crew carousel on the detail person page

---

src/frontend/src/components/LoginForm/LoginForm.css
src/frontend/src/components/NavBar/NavBar.css
src/frontend/src/components/NavBar/Navbar.jsx

This pull request includes changes to the layout and styling of the `LoginForm` and `NavBar` components in the frontend. The most important changes include adjustments to the width of the login form and dropdown menu, as well as the addition of a responsive design for smaller screens.
Styling updates:
* [`src/frontend/src/components/LoginForm/LoginForm.css`](diffhunk://#diff-6107dfe4fdcda393a8af14a926f0ece518481636976cc57196d0caa73aed7ab3L2): Removed the `min-width` property from the `.login-form` class, ensuring the login form takes up the full available width.
* [`src/frontend/src/components/NavBar/NavBar.css`](diffhunk://#diff-8be15b8475d9d1341111739f871b109a9bd309425b96e2a86c160ed0c65c3489R9-R25): Added styles for the `.dropdown-menu.show` and `.login-container` classes to set their …

fix: login styling

---

README.md
src/frontend/src/App.jsx
src/frontend/src/components/AdvancedSearchForm/AdvancedSearchForm.jsx
src/frontend/src/components/BackgroundContainer/BackgroundContainer.css
src/frontend/src/components/MediaGrid/MediaGrid.jsx
src/frontend/src/components/NavBar/Navbar.jsx
src/frontend/src/components/SearchForm/SearchForm.jsx
src/frontend/src/components/UpdateProfileForm/UpdateProfileForm.jsx
src/frontend/src/contexts/SearchContext.jsx
src/frontend/src/contexts/index.js
src/frontend/src/hooks/index.js
src/frontend/src/hooks/useSearch.js
src/frontend/src/pages/HomePage.jsx
src/frontend/src/pages/PersonOverviewPage.jsx
src/frontend/src/pages/ProfilePage.jsx
src/frontend/src/pages/SearchPage.jsx
src/frontend/src/services/mediaService.js
src/frontend/src/services/personService.js
src/frontend/src/services/tmdbService.js

> [!TIP]
> Review the PR by going through each commit
This PR introduces person results on the search result page, as well as introduces a context for managing search queries across pages.
The `SearchContext` allows for storing the search query between pages and showing it inside the form after navigation
Additionally fix logout button on user page.

feat: show person results on search page

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/ActionDropdown/ActionDropdown.jsx
src/frontend/src/components/BookmarkList/BookmarkList.jsx
src/frontend/src/components/CompletedList/CompletedList.jsx
src/frontend/src/components/MediaActions/MediaActions.jsx
src/frontend/src/utils/index.js
src/frontend/src/utils/rewatchabilityMap.js

This pull request introduces the `react-awesome-stars-rating` package and integrates a rating feature into various components. Key changes include updating dependencies, modifying the `ActionDropdown` and `BookmarkList` components to handle ratings, and adding a rewatchability map utility.
* Added `react-awesome-stars-rating` to `package.json` and `package-lock.json`. [[1]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR15) [[2]](diffhunk://#diff-9eaa8c31e85b60ae25c139f2d6363cc9dcb6926125b5bf1d0cac092547e8cfcbR3599-R3642) [[3]](diffhunk://#diff-12ee508ecc1901fe1a1d71ed459dba8454f3160983ee18b2c51b76ade45235d3R18)
* [`ActionDropdown.jsx`](diffhunk://#diff-393ff9532e25169b4d5603c3990d9636a13b0b007bbdb525f2f713ac96e9185aL1-R31): Added `ReactStarsRating` …

feat: dropdown for rewatchability with very low low medium high very high instead of numbers

---

src/frontend/src/components/GeneralCarousel/GeneralCarousel.jsx
src/frontend/src/components/MediaCard/MediaCard.jsx
src/frontend/src/components/MediaCarousel/MediaCarousel.jsx
src/frontend/src/components/MediaGrid/MediaGrid.jsx
src/frontend/src/components/MediaInformation/MediaInformation.jsx
src/frontend/src/components/PersonCard/PersonCard.jsx
src/frontend/src/components/PersonInformation/PersonInformation.jsx
src/frontend/src/components/PersonsCarousel/PersonsCarousel.jsx
src/frontend/src/components/PersonsGrid/PersonsGrid.jsx
src/frontend/src/hooks/usePaginatedData.js
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/pages/MediaOverviewPage.jsx
src/frontend/src/pages/PersonDetailPage.jsx
src/frontend/src/pages/PersonOverviewPage.jsx
src/frontend/src/pages/SearchPage.jsx

This pull request includes significant changes to remove the `loading` state and `isLoading` prop from various components and hooks in the frontend codebase. The changes aim to simplify the code and improve performance by removing unnecessary loading indicators. No prop drilling.
* [`src/frontend/src/components/GeneralCarousel/GeneralCarousel.jsx`](diffhunk://#diff-2c03e91f674a9b55cf95d26d4a7f02e7a7294078d0cd8e57efc25d74d8c52503L8): Removed `loading` prop and adjusted logic to use `items.length` instead. [[1]](diffhunk://#diff-2c03e91f674a9b55cf95d26d4a7f02e7a7294078d0cd8e57efc25d74d8c52503L8) [[2]](diffhunk://#diff-2c03e91f674a9b55cf95d26d4a7f02e7a7294078d0cd8e57efc25d74d8c52503L25-R27) [[3]](diffhunk://#diff-2c03e91f674a9b55cf95d26d4a7f02e7a7294078d0cd8e57efc25d74d8c52503L56-R55)
* …

refactor: change loading state to be controlled by the items id

---

src/frontend/src/components/BookmarkList/BookmarkList.jsx
src/frontend/src/components/CompletedList/CompletedList.jsx
src/frontend/src/components/CreditsList/CreditsList.jsx
src/frontend/src/components/InfoRow/InfoRow.jsx
src/frontend/src/components/MediaCard/MediaCard.jsx
src/frontend/src/components/MediaTypeBadge/MediaTypeBadge.jsx
src/frontend/src/components/index.js
src/frontend/src/pages/MediaDetailPage.jsx

This pull request involves renaming the `MediaCardBadge` component to `MediaTypeBadge` across various files for consistency and clarity. Additionally, there are some minor updates to the `InfoRow` component's styling. Below are the most important changes:
Component Renaming:
* [`src/frontend/src/components/BookmarkList/BookmarkList.jsx`](diffhunk://#diff-4e9400a52fdedad8c3b85878bea8813f5df88185cc71ebb6f8ddbd2b8c92f1c9L21-R21): Renamed `MediaCardBadge` to `MediaTypeBadge` in both the import statement and component usage. [[1]](diffhunk://#diff-4e9400a52fdedad8c3b85878bea8813f5df88185cc71ebb6f8ddbd2b8c92f1c9L21-R21) [[2]](diffhunk://#diff-4e9400a52fdedad8c3b85878bea8813f5df88185cc71ebb6f8ddbd2b8c92f1c9L115-R115)
* [`src/frontend/src/components/CompletedList/CompletedList.jsx`](diffhunk://#di …

feat: use badge for movie type everywhere, renaming from MediaCardBadge to MediaTypeBadge

---

src/frontend/src/components/MediaCard/MediaCard.jsx
src/frontend/src/pages/PersonDetailPage.jsx

This pull request includes updates to the `MediaCard` component and the `PersonDetailPage` to enhance functionality and improve layout. The most important changes include making the `MediaCard` optionally non-clickable, adding debug logging, and adjusting the layout of the `PersonDetailPage`.
Enhancements to `MediaCard` component:
* [`src/frontend/src/components/MediaCard/MediaCard.jsx`](diffhunk://#diff-2b4d63119b92cc5a858465e0c9c311a243c8c635060649cff32436d79dd59ba2R13-R32): Added a `clickable` prop to make the `MediaCard` optionally non-clickable. Updated the `handleClick` function and the `div` element to respect the `clickable` prop.
Improvements to `PersonDetailPage`:
* [`src/frontend/src/pages/PersonDetailPage.jsx`](diffhunk://#diff-410656ca5388cae2df048377b54b05faa0a9fe86341734904e …

fix: Known for movies

---

src/frontend/src/components/PersonInformation/PersonInformation.jsx
src/frontend/src/pages/PersonDetailPage.jsx
src/frontend/src/services/tmdbService.js

This pull request includes significant updates to the `PersonInformation` and `PersonDetailPage` components to enhance the display of person images using a carousel. Additionally, a new service function has been introduced to fetch person images from TMDB.
Enhancements to `PersonInformation` component:
* [`src/frontend/src/components/PersonInformation/PersonInformation.jsx`](diffhunk://#diff-8489d66eb09f3883d272c95424e506123988b952cb8e01be68730c336909694bR9): Imported `Carousel` from `react-bootstrap` and added a carousel to display multiple images if available. [[1]](diffhunk://#diff-8489d66eb09f3883d272c95424e506123988b952cb8e01be68730c336909694bR9) [[2]](diffhunk://#diff-8489d66eb09f3883d272c95424e506123988b952cb8e01be68730c336909694bL40-R69)
* …

feat: add addtional images for a person

---

src/frontend/src/components/Pagination/Pagination.jsx
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/pages/SearchPage.jsx
src/frontend/src/services/mediaService.js
src/frontend/src/services/personService.js
src/frontend/src/utils/fetchAllPages.js

This pull request includes several changes to the frontend codebase, focusing on simplifying the search functionality and improving pagination handling. The most important changes include modifications to the `Pagination` component, `MediaDetailPage`, `SearchPage`, and related services.
Improvements to search functionality:
* [`src/frontend/src/pages/MediaDetailPage.jsx`](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecL22-R22): Removed the use of `fetchAllPages` for fetching titles and adjusted the dependency array in the `useEffect` hook to avoid infinite loops. [[1]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecL22-R22) [[2]](diffhunk://#diff-9067da5199ca855ad6e34c7c96e7704c01a34040a5826da405606ca2edcb83ecL104-R104) …

Fix: search result page refreshing all items

---

src/frontend/src/components/SearchForm/SearchForm.jsx

This pull request includes significant improvements to the search history functionality in the `SearchForm` component. The changes focus on ensuring the uniqueness of search history items and improving the deletion process.
Improvements to search history functionality:
* [`src/frontend/src/components/SearchForm/SearchForm.jsx`](diffhunk://#diff-d63c9b4d81c977c527ab14269171efd40dff36598801da6596c94eb85680aa76L34-R116): Modified the logic to fetch user search history to ensure the uniqueness of search history items by filtering out duplicates based on `searchText`.
* [`src/frontend/src/components/SearchForm/SearchForm.jsx`](diffhunk://#diff-d63c9b4d81c977c527ab14269171efd40dff36598801da6596c94eb85680aa76L34-R116): Updated the `handleDelete` function to delete all search history items with …

fix: remove duplicate of search results

---

src/frontend/src/components/CreditsList/CreditsList.jsx
src/frontend/src/components/GeneralCarousel/GeneralCarousel.jsx
src/frontend/src/components/MediaCarousel/MediaCarousel.jsx
src/frontend/src/components/PersonsCarousel/PersonsCarousel.jsx
src/frontend/src/hooks/usePaginatedData.js
src/frontend/src/pages/MediaDetailPage.jsx
src/frontend/src/pages/PersonDetailPage.jsx
src/frontend/src/pages/SearchPage.jsx

This PR fixes the following bugs:
- no placeholder on carousel causing content to jump around during page loading
- credits not displaying tv series correctly
- job category not displaying if not actor
- fetch all state was not cleared when navigating from one person to another, this caused all credits to be loaded if they were loaded on the previous person
- see all button not working after navigating between persons
- query not updating search params
Also did some refactoring and removed unnecessary callback methods

fix: minor UI bugs
